# GitHub Pages Configuration for Travel Rule API Documentation

# Site settings
title: "Travel Rule API Documentation"
description: "Complete API documentation for Travel Rule compliance services"
url: "https://yourusername.github.io"
baseurl: "/bitgo-demo/travel-rule-doc"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - deploy.sh
  - components
  - docs

# Include files
include:
  - openapi.yaml
  - index.html

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
