name: Deploy Travel Rule API Docs to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths: [ 'travel-rule-doc/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'travel-rule-doc/**' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build documentation
        run: |
          # Copy travel-rule-doc to build directory
          mkdir -p _site
          cp -r travel-rule-doc/* _site/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'travel-rule-doc'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
